✨[Feat]: TimeModalView Present 기능 추가
doyeonjeong/Tublock pull request #20
Opened 2023-04-11 07:09 UTC by doyeonjeong

## 시뮬레이터
![Simulator Screen Recording - iPhone 14 Pro - 2023-04-11 at 15 57 01](https://user-images.githubusercontent.com/108422901/231082575-0e6326ac-74bd-421a-8b56-d0e99a665fa5.gif)

## 수정사항
1. 직관적인 로직과 터치 이벤트 target 편의를 위해 `_timeSettingView`를 `_timeSettingButton`로 변경
2. `_timeSettingButton`를 눌렀을 때 Modal 띄우는 것 까지만 추가했습니다..!

Close #9

2023-04-11 08:57 UTC, kangddong requested changes
전반적으로 기능 구현이 빨리되어서 놀랐어요 !! 비비 최고 !!👍👍👍

이번에 바쁜 일정 속 비비의 책임감이 보이는 코드였던거 같아서 눈물이 날뻔했네요 
이거 풀리퀘 올리고 쓰러진거 아니죠 ?? 건강 챙기면서해요 !!

2023-04-11 08:57 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +    var viewModel: SetMaximumViewModel = DefaultSetMaximumViewModel()
Default 이름의 의도가 무엇일까요 ? BaseViewModel과 같은 기본이 되는 확장성을 염두해두고 명명한건가요 ?

2023-04-11 08:57 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        _timeSettingButton.addSubview(_timeLabel)
`_timeLabel` 변수의 목적이 `_timeSettingButton` 버튼에 `AttributedText`를  설정하기 위함일까요 ?🤔
`UIButton`에는 `_timeLabel` 변수의 역할을 대신할  `.setAttributedTitle(title: NSAttributedString, for: UIControl.State) ` 메소드가 있어요 !😃
그 이상 불필요한 변수라면 메소드로 대체해주세요 ! 🤣

2023-04-11 08:57 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> -        _timeSettingView.addSubview(_timeLabel)
비비가 구조 잡은 `ViewController` 에서는 함수가 많은 일을 하지않게 잘게 쪼갰고,
추상화하여 같은 코드레벨을 가지게끔 작성해서 코드가 보기 좋고 너무 이뻣는데 ..!🫢🫢🫢
 `SetMaximumView` 파일에서는 그러한 규칙과 통일성이 보이지않네요 ! 
규칙과 통일성을 지키지 못한 이유가 있나요 ? 😅

2023-04-11 08:57 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
>          _timeLabel.attributedText = attributedText
`_timeSettingButton.setAttributedTitle(attributedText, for: .normal)`
코드로 고칠 수 있겠지만 

```swift
 private lazy var _timeSettingButton: UIButton = {
         let button = UIButton()
         button.layer.cornerRadius = 14
         button.backgroundColor = .white
         button.addTarget(self, action: #selector(_showTimePickerModalView), for: .touchUpInside)
         return button
     }()
```

위에서 선언한 이 코드의 선언과 표현이 분리되어있어 혼란을 발생시킬거같아요
`.setAttributedTitle(title: NSAttributedString, for: UIControl.State)` 의 입력 파라미터인 `NSAttributedString` 타입을 `return` 시켜서 사용하는건 어떨까요 ?😊 `Swift`는 함수형언어 패러다임도 차용한 언어니까요 ! 😊😊

2023-04-11 08:57 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +    func update(selectedTime: BlockTime) {
이 메소드는 접근제한자는 internal인데 pickerviewDelegate 구현부에서만 사용된다면 접근제한자를 변경해야할것같아요 !

2023-04-11 08:57 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        hours = selectedTime.hours
현재 view에서 hours, minutes 가진 이유가 
**_updateAttributedText** 에 사용되어 버튼의 텍스트를 업데이트하는 용도라면
클래스 프로퍼티로 가지기 보다 _updateAttributedText 입력 파라미터로 쓰여도 되지않을까요 ?
그리고, hours, minutes 는 MVVM 구조상 View가 몰라야한다고(클래스 내부 프로퍼티로서 선언하지않아도)  생각해요 !

그렇게 메소드를 리팩토링하면 Button 속성 값을 설정할 때 문제가 겪을 수도 있어요(조금 더 고민하면 겪지않을 수도 있고요 😄)

2023-04-11 08:57 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        update(selectedTime: time)
이때 ViewModel에 업데이트를
ViewModel은 Service에 시간 변화가 있다고 알려줘야하지않을까요 ?

2023-04-11 08:57 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        viewModel.update(selectedTime: (hours: hours, minutes: minutes))
View 와 ViewModel 데이터바인딩 방식이 궁금합니다 ~!
pickerModalView를 보여주는 기능에서 viewModel을 현재 시간으로 업데이트 한다는 말이 이해가 잘 되지않아요!
설명 해주실 수 있을까요 ?

2023-04-11 08:57 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        guard let keyWindow = UIApplication.shared.windows.first(where: { $0.isKeyWindow }),
**'windows' was deprecated in iOS 15.0: Use UIWindowScene.windows on a relevant window scene instead**
현재 `windows`는 `deprecated` 되었는데
다른 방식이 없어서 이렇게 사용하신걸까요 ?

2023-04-11 08:57 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        guard let viewController = _findViewController() else { return }
`TimePicker`를 표시할 뷰 컨트롤러 찾지 못한 경우에는 어떤 동작을 하나요 ?

2023-04-11 08:57 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/TimePickerModalView.swift
> +        view.backgroundColor = UIColor.black.withAlphaComponent(0.5)
비비가 구조 잡은 ViewController 에서는 함수가 많은 일을 하지않게 잘게 쪼갰고,
추상화하여 같은 코드레벨을 가지게끔 작성해서 코드가 보기 좋고 너무 이뻣는데 ..!🫢🫢🫢
TimePickerModalView 파일에서는 그러한 규칙과 통일성이 보이지않네요 !
규칙과 통일성을 지키지 못한 이유가 있나요 ?

2023-04-11 08:57 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        _timeSettingButton.snp.makeConstraints { make in
`UIStackView.distribution` 기본 값이 `.fill` 이어서 그렇지않을까요 ?
UI 구조상 `.fillEqually`를 통해서도 가능할거에요 ㅎㅎ

AutoLayout과 StackView가 많이 어려우면 같이 공부 해볼까요 ?

2023-04-17 04:54 UTC, doyeonjeong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +    var viewModel: SetMaximumViewModel = DefaultSetMaximumViewModel()
앗 넵 확장성을 고려해서 작성해본 것 맞습니다..!
프로토콜을 자주 다뤄보지 않기도 했고, '유연한' 코드를 작성한다는 의미를 아직 잘 모르는 것 같아요..🥲
그래서 시도해봤는데 조금 일러보일까요? 조언을 구해봅니다..!

[참고했던 것](https://github.com/kudoleh/iOS-Clean-Architecture-MVVM/blob/master/ExampleMVVM/Presentation/MoviesScene/MovieDetails/ViewModel/MovieDetailsViewModel.swift)

2023-04-17 04:56 UTC, doyeonjeong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> -        _timeSettingView.addSubview(_timeLabel)
헤헷... 작업을 빨리 끝내야한다는 마음이 코드에 드러난 것 같습니다 ...🥹
뭔가 분주하네요... 다음엔 말씀해주신 내용을 좀 더 신경써서 PR 하겠습니다!

2023-04-17 04:59 UTC, doyeonjeong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        update(selectedTime: time)
제가 Service에 대한 개념을 아직 파악하지 못하고 있는 것 같습니다!
그래서 챗지피티한테 뭐라고 물어봐야할지도 모르는 상황인데, 혹시 추천해줄만한 아티클이 있을까요?

2023-04-17 05:06 UTC, doyeonjeong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        guard let keyWindow = UIApplication.shared.windows.first(where: { $0.isKeyWindow }),
방법을 찾아보긴 했지만 어떻게 사용하는지를 모르겠어서
일단 작업기한 내에 PR하고 나중에 고치면 되지 않을까..? 했습니다 😅
[UIWindowScene 찾아본 것](https://developer.apple.com/documentation/uikit/uiwindowscene/)

2023-04-17 05:08 UTC, doyeonjeong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/TimePickerModalView.swift
> +        view.backgroundColor = UIColor.black.withAlphaComponent(0.5)
🥲 작업 기한을 맞춰야 한다는 조급한 마음이 불러낸 대참사입니다... 흑흑 다음엔 주의하겠습니다 이부분 !

2023-04-17 05:09 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        update(selectedTime: time)
비즈니스 로직, 즉 Model 안에 포함 된 부분이라고 생각하면 될거같아요 !

2023-04-17 05:10 UTC, doyeonjeong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        guard let viewController = _findViewController() else { return }
음 ... 뷰 컨트롤러를 찾지 못할거라는 생각에는 못 미쳤습니다..!
뷰 컨트롤러를 찾기 못하는 경우가 발생하나요? 발생한다면 원인은 어떤거라고 생각하시나요?

2023-04-17 05:18 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        guard let keyWindow = UIApplication.shared.windows.first(where: { $0.isKeyWindow }),
```swift
guard let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
           let delegate = windowScene.delegate as? SceneDelegate else { return nil }
guard let rootViewController = delegate.window?.rootViewController else { return nil }
```

이 코드로 대체 가능합니다아

2023-04-17 05:18 UTC, doyeonjeong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        guard let keyWindow = UIApplication.shared.windows.first(where: { $0.isKeyWindow }),
멋있엉 ... 감사합니다

2023-04-17 05:19 UTC, doyeonjeong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        update(selectedTime: time)
아하 알겠습니다

2023-04-17 05:22 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        guard let viewController = _findViewController() else { return }
찾지 못하는 경우는 발생하더라구요
원인은 A VC에서 _findViewController호출을 하면서 A 이외의 다른 VC로 화면이동이 되던 경우에 경험해봤습니다.
-> 화면이동(present, push)은 비동기이기 때문에 화면 이동 후라던지 호출, 혹은 로직의 실행 시점을 명확히 했어야했습니다!! 


현재 코드에서는 1개의 VC에서 present 하기에 그런 사이드 이펙트 발생하지않을 것으로 예상되지만 옵셔널 바인딩이 실패했을 때 return 이 없어도 괜찮을지에 대한 질문이었어요 !

2023-04-17 05:27 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        update(selectedTime: time)
일단 제 요점은 View -> ViewModel -> Model 로 흐름이 되었을 때
View(PickerModal View) -> ViewModel의 방향이었어요
update 메소드는 view의 시간만을 변경하기 때문에 viewmodel에 대한 업데이트도 필요하다고 생각했어요 

아래는 제가 생각한 흐름입니당 !

--data flow start--
picker -> viewmodel update -> model 
model (callback)-> viewModel (callback) -> View (update time)
--data flow end--

2023-04-17 05:28 UTC, doyeonjeong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        viewModel.update(selectedTime: (hours: hours, minutes: minutes))
아 이 부분도 급히 만들다보니 스스로도 혼동이 좀 있었던 부분인 것 같습니다.

처음엔 `SetMaximumView`에서 `_timeSettingButton`을 눌러 `TimePickerView`를 Present할 때 `_timeSettingButton`안에 있는 `_timeLabel`값을 viewModel에 업데이트할 후 그 값을 `TimePickerView`에서 Label 등을 통해 화면에 노출 시키려고 했던 것 같습니다.

근데 지금 짚어주신 점을 살펴보니 굳이 ...? 라는 생각이 드네요.
`TimePickerView`에서 `viewModel`과 직접 소통하면 될 일이고,
`SetMaximumView`에서는 `TimePickerView`에서 설정된 값을 `viewModel`을 통해 가져오기만 하면 될 것 같네요.

이 방식으로 수정하겠습니다!
불필요한 부분 캐치해주셔서 감사해요 아렉스!!!! 진짜 꼼꼼한 리뷰 ... 👍🏻

2023-04-17 05:30 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        viewModel.update(selectedTime: (hours: hours, minutes: minutes))
저도 아직 ... MVVM를 명확하게 이해하지못해서 비비에게 설명을 부족하게한 것 같아요
그래도 제가 말한 의도 바로 이해해줘서 고마워요 
비비 최고 👍

2023-04-17 05:30 UTC, doyeonjeong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        update(selectedTime: time)
아~~~ ViewModel에서 제가 빠트렸군여??? 진짜진짜진짜 이해완료...! 얼른 수정하겠습니다 👍🏻

2023-04-17 05:36 UTC, doyeonjeong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        guard let viewController = _findViewController() else { return }
아하 그렇군여 ..
그러면 음 ... `화면 호출을 해야하는 뷰 컨트롤러()` 해서 return 시켜야겠다는 생각이 드네요!
이건 어떻게 생각하시나요?

2023-04-17 05:40 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        guard let viewController = _findViewController() else { return }
현재 로직에서는 큰 문제 없을거같지만 .. 

제 우려는 보통 저런 메소드는 Util 로 빼서 공용으로 사용하는 경우가 많아서 한 것이었어요 !
Util로 빼서 사용하는게 아니라면 사실 현재 VC에서 옵셔널 바인딩에서 현재 View를 못 찾아서 실패하는 경우는 저도 없다고 생각해서
굳이 추가할 필요까지는 없을거같아요 
비비가 현재 로직에서도 실패할 것으로 생각되면 실패 시에 대한 에러처리는 해주는게 좋긴하죠 !

2023-04-17 05:43 UTC, doyeonjeong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        guard let viewController = _findViewController() else { return }
오 저런걸 Util로 빼서 작업하는군여?
알겠습니다! 이번 로직에서는 따로 추가하진 않겠지만 앞으로는 고려해서 작업해야겠어요!

2023-04-18 02:14 UTC, doyeonjeong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        _timeSettingButton.snp.makeConstraints { make in
UIStackView.distribution 기본값이 .fill 인거 이번에 처음 알았네요!
StackView 사용하기 전에 공식문서 한번씩 훑고 사용하는 연습을 해봐야겠어요 ㅎㅎ

2023-04-18 03:53 UTC, kangddong requested changes
비비 작업속도가 참 빠르네요 ~! 바쁘신데도 고생 많으셨어요 !! 
근데 빌드 우려가는 부분이 있어서 request changes 로 상태 올렸어요 !!

2023-04-18 03:53 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        _setupContentsView()
_setUpView() 라는 이름 때문일까요 ? 
기존에는 View 추가, View의 constraints 설정 이렇게 구분을 했었는데,
이번에는 기존 코드와 컨셉이 다른 코드구분이네요 ?
코드레벨은 동일하게 맞췄지만 기존과 다른 컨셉이라서 코드를 읽는데 조금 불편함이 느껴졌어요 !!
어떤 의도를 가지고 리팩토링한걸까요 ?

2023-04-18 03:53 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        _setupTitleLabel()
`_titleLabel`, `_descriptionLabel` 의 View의 추가 시점은 `_setupHorizontalStackView()`에서 이뤄지는데 

`_setupHorizontalStackView()`의 호출 시점은 `_setupDescriptionLabel()` ,`_setupHorizontalStackView()` 메소드보다 늦게 불려지네요? 의도한 동작일까요 ?
기존과 다르게 UI Object 기준으로 메소드를 리팩토링한 기준은 무엇인가요 ?

2023-04-18 03:53 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/TimePickerModalViewController.swift
> +final class TimePickerModalViewController: UIViewController {
이젠 PickerViewController가 되어서 명확하게 구분이 가는거 같아요 !👍

2023-04-18 03:53 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +    var viewModel: SetMaximumViewModel = DefaultSetMaximumViewModel()
class 명은 `SetMaximumViewModel` 로 이름이 바뀌었는데요 여전히 `DefaultSetMaximumViewModel` 이라서 빌드시에 오류가 날거같은데 괜찮나요 ?
그리고 파일명 또한 `DefaultSetMaximumViewModel` 라서 class 명이 `SetMaximumViewModel` 바뀐거라면
파일명도 바꿔야할거같아요 !

2023-04-18 12:52 UTC, kangddong approved these changes
비비 고생했어요 !!
시험 기간 화이팅 !!

2023-04-18 12:55 UTC, kangddong commented
이번 피처는 머지까지 짧지않은 시간이 걸렸지만, 끝까지 집중력있게 같이 해줘서 고마워요
저 또한 피처에 대해서 이렇게 길게 얘기 나누면서 협업한 경험이 처음이라 서툴렀던 점이 있을거같아요
그래도 좋게 봐줘서 항상 고마워요

2023-04-18 12:55 UTC, merged

2023-04-18 13:02 UTC, doyeonjeong commented
처음은 다 서툴고 어렵죠
그래도 어떤 문제든 소통으로 해결할 수 있다고 믿어요 ㅎㅎ
저도 이런 협업을 아렉스랑 경험해서 다행이라고 생각해요
일하느라 힘들텐데 꼼꼼한 리뷰와 피드백으로 이유있는 코드를 작성할 수 있게 도와줘서 저야말로 고마워요