🎨[Design]: PickerView UI 디자인 #37
doyeonjeong/Tublock pull request #41
Opened 2023-04-27 16:27 UTC by doyeonjeong

## 로컬라이징 설정
<div>
<img src="https://user-images.githubusercontent.com/108422901/234911650-392464a9-795c-4764-8d9e-6be6461e68ef.gif"/>
<img src="https://user-images.githubusercontent.com/108422901/234928116-ae74cd31-b681-4cef-a3cf-531f3d7236f5.gif"/>
</div>

체크박스에 이쁘게 초록색 체크 버튼뜨게 설정했는데 시뮬레이터 녹화는 안보이네요...🥲

<div>
<img height="80" alt="스크린샷 2023-04-28 오전 12 31 28" src="https://user-images.githubusercontent.com/108422901/234911989-6b4fba0b-fcc6-4ee7-8423-58883ab13468.png">
<img height="80" alt="스크린샷 2023-04-28 오전 1 22 28" src="https://user-images.githubusercontent.com/108422901/234927329-8eca02a3-936a-41f4-85fe-b364aace90b2.png">
</div>

2023-04-28 05:20 UTC, kangddong requested changes
Localizing 부터 CheckBox Cusom Button 등 너무 잘 봤어요 !

2023-04-28 05:20 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        timePicker.modalPresentationStyle = .automatic
`.automatic`을 이용하면 시스템에 따라서 스타일이 변경될 수가 있기 때문에 의도한 스타일을 명확하게 지정해주는건 어떨까요 ?
`.pageSheet`이라던지요

2023-04-28 05:20 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/TimePickerModalViewController.swift
> +class CheckBox: UIButton {
서브클래싱을 해서 새로운 객체로 만든 건 너무 좋은 아이디어같아요 !
UIButton을 서브클래싱했다면 `CheckBoxButton`과 같이 클래스를 명확하게 표기해주는게 좋을거같아요 !

2023-04-28 05:20 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/TimePickerModalViewController.swift
> +    @objc func buttonCliked(_ sender: UIButton) {
CheckBox 객체를 외부에서 생성했을 때 의도치않는 동작을 막기위해서는
private 접근제한자를 사용하면 좋을거같아요 !

2023-04-28 05:20 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/TimePickerModalViewController.swift
> +    @objc func buttonCliked(_ sender: UIButton) {
sender를 사용하지않고 self로 접근하는 메소드인데 사용하지않는 매개변수라면 지워야하지않을까요 ?
의도된 작성인지 궁금합니다

2023-04-28 05:20 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/TimePickerModalViewController.swift
> +        _setBackground()
기존 코드와 통일감 있게 리팩토링해서 코드를 읽을 때 일관성있게 읽히는거 같아서 좋은거같아요 감사합니다

2023-04-28 05:20 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/ViewModel/SetMaximumViewModel.swift
> +            string: " hours ".localized,
file changed 가 아니라서 코드를 선택하지 못했는데 
ViewModel 코드이니까 8번 째 줄 UIKit 대신 Foundation으로 바꿔야할거같습니다
아마도 UIFont 때문에 UIKit를 사용한 것 같은데 같이 고민이 필요할거같아요

2023-04-28 05:22 UTC, doyeonjeong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/TimePickerModalViewController.swift
> +    @objc func buttonCliked(_ sender: UIButton) {
앗.. Button에 addTarget하는거라서 습관적으로 썼네요 지워야겠습니다

2023-05-01 00:26 UTC, doyeonjeong commented on Tublock/Tublock/Resources/Supporting Files/Localizable.strings
> +"min" = "분";
Time Picker View에 표시되는 라벨인데 minutes로 표기하니까 거기만 너무 길어보이더라구요!
"min" 으로 작성하고 로컬라이징 할 때 "분"으로 표기하는게 더 나아보이는데 어떤가요?

2023-05-01 00:35 UTC, doyeonjeong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/ViewModel/SetMaximumViewModel.swift
> +            string: " hours ".localized,
<img width="774" alt="스크린샷 2023-05-01 오전 9 34 33" src="https://user-images.githubusercontent.com/108422901/235383725-34486d01-eb5d-4855-8a3b-d7d67b0648cd.png">
핫 .. 이거 `UIKit`을 써야 하는 것 같은데, 이 함수를 `SetMaximumView.swift`파일 하단의 함수로 이동시킬까요?

2023-05-01 00:46 UTC, doyeonjeong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/TimePickerModalViewController.swift
> +    @objc func buttonCliked(_ sender: UIButton) {
아 버튼 작업하면서 `sender` 사용하는 코드로 업데이트 했습니다! 사용하는 코드니 그대로 두겠습니다 😊
```swift
@objc private func _checkBoxCliked(_ sender: UIButton) {
        sender.isSelected.toggle()
        sender.isSelected == true ? (_confirmButton.isHidden = false) : (_confirmButton.isHidden = true)
    }
```

2023-05-01 00:50 UTC, doyeonjeong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
> +        timePicker.modalPresentationStyle = .automatic
`.pageSheet`로 변경 완료!

2023-05-01 00:51 UTC, doyeonjeong commented on Tublock/Tublock/Resources/Supporting Files/Localizable.strings
> +" hours " = " 시간 ";
수정 완료! [940bb4f](https://github.com/doyeonjeong/Tublock/pull/41/commits/940bb4f677fc3de5554f99a7eacf546010af4c88)

2023-05-02 02:13 UTC, kangddong commented on Tublock/Tublock/Resources/Supporting Files/Localizable.strings
> +"min" = "분";
[Swift API design guidelines](https://www.swift.org/documentation/api-design-guidelines/) 에 따르면

> Clarity is more important than brevity. Although Swift code can be compact, it is a non-goal to enable the smallest possible code with the fewest characters. Brevity in Swift code, where it occurs, is a side-effect of the strong type system and features that naturally reduce boilerplate.

간결함보다는 명확함이 중요하다고 말하고있고, 다른 Localizable String key 또한 명확한 의미를 담고있어서 통일성을 갖추면 좋을 것 같습니다

2023-05-02 02:14 UTC, doyeonjeong commented on Tublock/Tublock/Resources/Supporting Files/Localizable.strings
> +"min" = "분";
알겠습니다 수정해서 반영해볼게요!

2023-05-02 03:26 UTC, kangddong approved these changes
이번 PickerView 고도화를하면서 로컬라이징이라던지
새롭게 배우면서 해야하는 부분이 있었을텐데 고생하셨어요 !!
남은 개발도 후딱 해버리자구여 !

2023-05-02 04:00 UTC, merged