✨[Feat]: 선택된 BlockTime 값 UserDefaults 연동
doyeonjeong/Tublock pull request #58
Opened 2023-05-08 11:28 UTC by doyeonjeong

Close #38

## 구현사항
![스크린샷 2023-05-08 오후 8 23 13](https://user-images.githubusercontent.com/108422901/236812154-afec1a7c-59d7-4379-8cb2-07ab50f0a7e0.png)

## 리뷰어 참고사항
`UserDefaultsManager.time` 연동처리 간단한 거였는데 이것부터 안해서 답답했을 것 같아요 ㅠㅠ 미안합니다
다음엔 빠르게 수정할 수 있는 일들 먼저 처리할게요! 기다려줘서 고마워요 🥹

2023-05-08 11:59 UTC, kangddong requested changes
저장에 대한 코드만 있고 저장된 값을 표시하는 코드가 없는거같아요
SetMaximumViewModel init 을 할 때 UDManger 값을 가지고 와야할듯합니다

2023-05-09 03:23 UTC, kangddong requested changes
loadTime() 메소드가 언제 사용 되는지 궁금해요 !

2023-05-09 03:23 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/TimePickerModalViewController.swift
> +            viewModel.selectedTime.hours = row
이렇게 뷰모델에 저장해주고 `saveTime()`를 통해서 저장해준 다음에
`loadTime()` 은 언제 사용되는걸까요 ?

2023-05-09 03:23 UTC, kangddong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/ViewModel/SetMaximumViewModel.swift
> +        selectedTime = UserDefaultsManager.time
현재 호출되는 코드가 없는 것 같은데 맞을까요 ?

비비가 생각하기에 UserDefaultsManager.time에 할당된 시간을 언제 불러서 어디에서 사용해야한다고 생각하나요 ?

2023-05-11 09:05 UTC, doyeonjeong commented on Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/TimePickerModalViewController.swift
> +            viewModel.selectedTime.hours = row
init할 때 같이 설정해줘야 했는데 누락했네요! 수정했습니다!

2023-05-11 11:10 UTC, doyeonjeong commented
# Update
`TimePickerModalViewController`가 `SetMaximumView`의 ViewModel 객체를 주입받아
선택된 시간을 확정했을 때 SetMaximumView에서도 확인되도록 변경했습닌다!

![Simulator Screen Recording - iPhone 14 Pro - 2023-05-11 at 18 02 47](https://github.com/doyeonjeong/Tublock/assets/108422901/585d7c2a-06a2-4df4-9e8f-53f617520e97)

2023-05-11 14:20 UTC, kangddong approved these changes
고생하셨어요 ! `SetMaximumView` 피처가 이제 끝났네요 !

2023-05-11 14:28 UTC, doyeonjeong commented
> 고생하셨어요 ! `SetMaximumView` 피처가 이제 끝났네요 !

드뎌...! 기다려줘서 고마워요..🥹

2023-05-11 14:29 UTC, merged